### ISSUE TITLE
Fails to build on Slackware 14.2 because missing file: support-log.h

### ISSUE THREAD

**Issue by eugeneia** [nicklan/pnmixer#137]
I fail to build pnmixer on Slackware 14.2 and get the following error:

```
gcc -DHAVE_CONFIG_H -I.  -DPACKAGE_DATA_DIR=\""/usr/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/share/locale"\" -pthread -I/usr/include/alsa -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -g -O2 -MT alsa.o -MD -MP -MF .deps/alsa.Tpo -c -o alsa.o alsa.c
alsa.c:31:25: fatal error: support-log.h: No such file or directory
```

Full build output below:

```
% ./configure --prefix=/usr
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether NLS is requested... yes
checking for intltool >= 0.40... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.22.2
checking for XML::Parser... ok
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for catalogs to be installed...  de fr it ru zh_CN
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ceil in -lm... yes
checking for x11... yes
checking for alsa... yes
checking for PACKAGE... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating data/desktop/Makefile
config.status: creating data/icons/Makefile
config.status: creating data/pixmaps/Makefile
config.status: creating data/ui/Makefile
config.status: creating man/Makefile
config.status: creating po/Makefile.in
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

=====================================
CONFIGURATION:
libnotify enabled..... yes
gtk version........... 3
=====================================

% make
Making all in data
make[1]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/data'
Making all in desktop
make[2]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/data/desktop'
LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../../po/.intltool-merge-cache ../../po pnmixer.desktop.in pnmixer.desktop
Generating and caching the translation database
Merging translations into pnmixer.desktop.
make[2]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/data/desktop'
Making all in icons
make[2]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/data/icons'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/data/icons'
Making all in pixmaps
make[2]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/data/pixmaps'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/data/pixmaps'
Making all in ui
make[2]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/data/ui'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/data/ui'
make[2]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/data'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/data'
make[1]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/data'
Making all in man
make[1]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/man'
Built pnmixer.1 from template
make[1]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/man'
Making all in po
make[1]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/po'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/po'
Making all in src
make[1]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/src'
make  all-am
make[2]: Entering directory '/home/max/tmp/pnmixer-0.7-rc1/src'
gcc -DHAVE_CONFIG_H -I.  -DPACKAGE_DATA_DIR=\""/usr/share"\" -DPACKAGE_LOCALE_DIR=\""/usr/share/locale"\" -pthread -I/usr/include/alsa -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -g -O2 -MT alsa.o -MD -MP -MF .deps/alsa.Tpo -c -o alsa.o alsa.c
alsa.c:31:25: fatal error: support-log.h: No such file or directory
compilation terminated.
Makefile:437: recipe for target 'alsa.o' failed
make[2]: *** [alsa.o] Error 1
make[2]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/src'
Makefile:318: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/max/tmp/pnmixer-0.7-rc1/src'
Makefile:372: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by eugeneia** [comment]
@hasufell Could you tell me the direct dependencies of pnmixer?

**Comment by hasufell** [comment]
https://github.com/nicklan/pnmixer#compilation-and-install

**Comment by hasufell** [comment]
ping, will close in the next few days if there is no feedback
